version: "3.8"

services:
  # FastAPI and Celery app service
  app:
    build: .
    container_name: telebot_app
    command: >
      sh -c 'uvicorn app:app --host 0.0.0.0 --port 5005'
    restart: always
    network_mode: "host"

  celery:
    build: .
    container_name: telebot_celery
    command: celery -A celery_config:celery_app worker -l info
    network_mode: "host"
    depends_on:
      - app